### Maker회원가입 요청 테스트

POST http://goforme.duckdns.org/user/signup
Content-Type: application/json

{
  "user": {
    "role": "MAKER",
    "nickName": "testUser2",
    "email": "testuser2@example.com",
    "password": "password123",
    "phoneNumber": "01012345678"
  },
 "profile": {
		"image": "DEFAULT_1",
    "serviceArea": ["SEOUL"],
    "serviceTypes": ["FOOD_TOUR"],
    "gallery": "sns url",
    "description": "한줄 소개",
    "detailDescription": "더 긴 소개 내용"
	}
  }

###
### 로그인 요청 테스트

POST https://goforme.duckdns.org/user/login
Content-Type: application/json

{
  "email": "testuser2@example.com",
  "password": "password123"
}


### 프로필 조회
GET http://localhost:4000/users/profile/032d7bd4-116c-467b-9352-a14b0d494ef9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzg1NzgwNDksImV4cCI6MTczODY2NDQ0OX0.yDCZo-C0jUQcU-AQWfiQkoGQ1-ig_X3rKO4fIQ-ey9M

### 받은요청

GET http://localhost:4000/plans/maker?isAssigned=true&tripType=FOOD_TOUR&tripType=SHOPPING&tripType=RELAXATION&tripType=CULTURE&tripType=ACTIVITY&tripType=FESTIVAL&orderBy=SCHEDULE_FIRST&page=1&pageSize=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc5NTg3ODUsImV4cCI6MTczODA0NTE4NX0.yqZkkI_nKwTa7pGegMneVO4Yld8VJJirQQ_s6TQdSus

###



###


POST http://localhost:4000/plans/10ceb118-9682-4c9e-9841-bca818022369/quotes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc3OTA0NTksImV4cCI6MTczNzg3Njg1OX0.uv2p3SygiuQsa18I76W6Odf_-bOMVcVpO2lIRDaWc04

{
  "price": 100000,
  "content": "견적 내용dddddd연습하기dddddddddd"
}

###

GET http://localhost:4000/quotes?isSent=true&page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc4Nzk5ODAsImV4cCI6MTczNzk2NjM4MH0.0rtZC-DSJDYEBu0e_Msm5dj4FkRFxE-HFKO3bFKKBxE

###

GET http://localhost:4000/plans/16865772-f792-4bb6-8ac8-504fcb4064e3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzc5NTg3ODUsImV4cCI6MTczODA0NTE4NX0.yqZkkI_nKwTa7pGegMneVO4Yld8VJJirQQ_s6TQdSus

###


GET http://localhost:4000/reviews/032d7bd4-116c-467b-9352-a14b0d494ef9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMzJkN2JkNC0xMTZjLTQ2N2ItOTM1Mi1hMTRiMGQ0OTRlZjkiLCJyb2xlIjoiTUFLRVIiLCJpYXQiOjE3Mzg1NzgwNDksImV4cCI6MTczODY2NDQ0OX0.yDCZo-C0jUQcU-AQWfiQkoGQ1-ig_X3rKO4fIQ-ey9M
