@HOST_NAME=http://localhost:4000

### 회원가입 요청 테스트

POST https://go-for-me.onrender.com/user/signup
Content-Type: application/json

{
  "user": {
    "role": "DREAMER",
    "nickName": "testUser",
    "email": "testuser@example.com",
    "password": "password123",
    "phoneNumber": "01012345678"
  },
  "profile": {
    "image": "DEFAULT_1",
    "tripTypes": [
      "FOOD_TOUR"
    ],
    "serviceArea": [
      "SEOUL",
      "INCHEON"
    ]
  }
}

### 로그인 요청 테스트

POST https://www.goforme.duckdns.org/auth/login
Content-Type: application/json

{
  "email": "dreamer1@test.com",
  "password": "12345678"
}


### 알림 테스트

GET https://go-for-me.onrender.com/notifications


### 찜한 메이커 조회
GET https://www.goforme.duckdns.org/follow?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1NTVkNDYzZS0zN2I2LTQxMGItOTA2MS0xMWE5ZDY4MjJiZGQiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczNzYxNzY2MywiZXhwIjoxNzM3NzA0MDYzfQ.YOUGCcJJ-TYPKGS4X9F3_0mdVGZOwaBS8vJOXspfBeA

### 리프레시 토큰
POST https://www.goforme.duckdns.org/users/refresh/token
Cookie: refreshToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczODU2NjY3MiwiZXhwIjoxNzM5MTcxNDcyfQ.PcJi_UulHX7BgCQzbVVER5jezoesd8HHvEazq9Nwxe8; Max-Age=604800; Path=/user/token/refresh; Expires=Mon, 10 Feb 2025 07:11:12 GMT; HttpOnly; Secure; SameSite=None

### 실시간 알림
POST https://goforme.duckdns.org/notifications
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczODU3MTAzNSwiZXhwIjoxNzM4NjU3NDM1fQ.AyxnnK68YvG5IPNmCK-yhtLhCSpF1-OhQ5MMX-hQFLw

### 실시간 알림

POST https://goforme.duckdns.org/notifications/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczODU3MTAzNSwiZXhwIjoxNzM4NjU3NDM1fQ.AyxnnK68YvG5IPNmCK-yhtLhCSpF1-OhQ5MMX-hQFLw


### 플랜 리스트 불러오기(dreamer)

GET https://www.goforme.duckdns.org/plans/dreamer?status=PENDING&status=CONFIRMED
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczODkwMjA2MywiZXhwIjoxNzM4OTg4NDYzfQ.Z552RQPGxWAdIon2aXEZ5z9D_OSfmEPcNTDYi9VEoYk


### 플랜 데이터 불러오기(dreamer)
GET https://www.goforme.duckdns.org/plans/0f61f8b9-7b29-4b82-86c7-f7ce8e418baa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTAzNDY3OSwiZXhwIjoxNzM5MTIxMDc5fQ.Q2fR2Np0O0uF1BznlyPL0z48hZeELsk4Ziro2SLrRaQ


### 견적 리스트 불러오기(dreamer)
GET https://www.goforme.duckdns.org/plans/181b2ef5-a7c6-4d62-a17e-542581693736/quotes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTAzNDY3OSwiZXhwIjoxNzM5MTIxMDc5fQ.Q2fR2Np0O0uF1BznlyPL0z48hZeELsk4Ziro2SLrRaQ

### 찜하기
POST https://www.goforme.duckdns.org/follow
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTAzNDY3OSwiZXhwIjoxNzM5MTIxMDc5fQ.Q2fR2Np0O0uF1BznlyPL0z48hZeELsk4Ziro2SLrRaQ

{
  makerId: "032d7bd4-116c-467b-9352-a14b0d494ef9"
}

###지도 통계 가져오기
GET https://www.goforme.duckdns.org/plans/groupCount
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTQyMTc1OCwiZXhwIjoxNzM5NTA4MTU4fQ.kraLArPuWV3kxY4iPakzgMS5ZGSRlvYY_-uBm182bXw


### 완료 가능 플랜 불러오기(dreamer)
GET https://www.goforme.duckdns.org/plans/dreamer?readyToComplete=true&page=1&pageSize=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTgwMDQxNSwiZXhwIjoxNzM5ODg2ODE1fQ.VKDq_T-dg2NK6xRC_2GeSNLXBLGD2SyIzbaAXWmfrfc


### 리뷰가능한 플랜 목록 조회(dreamer)
GET https://www.goforme.duckdns.org/plans/dreamer?reviewed=false&page=1&pageSize=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTgwMDQxNSwiZXhwIjoxNzM5ODg2ODE1fQ.VKDq_T-dg2NK6xRC_2GeSNLXBLGD2SyIzbaAXWmfrfc


### 작성한 리뷰 목록 조회(dreamer)
GET https://www.goforme.duckdns.org/reviews/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTgwMDQxNSwiZXhwIjoxNzM5ODg2ODE1fQ.VKDq_T-dg2NK6xRC_2GeSNLXBLGD2SyIzbaAXWmfrfc


### 완료 가능 플랜 불러오기(dreamer)
GET https://www.goforme.duckdns.org/plans/dreamer?readyToComplete=true&page=1&pageSize=6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2Njg4NWEzYy01MGY0LTQyN2ItOGE5Mi0zNzAyYzY5NzZmYjAiLCJyb2xlIjoiRFJFQU1FUiIsImlhdCI6MTczOTgwMDQxNSwiZXhwIjoxNzM5ODg2ODE1fQ.VKDq_T-dg2NK6xRC_2GeSNLXBLGD2SyIzbaAXWmfrfc
